spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/exceptiontest
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibenate:
        format_sql: true
        use_sql_comment: true

logging.level:
  org.hibernate.SQL: debug
